### ISSUE TITLE
Inaccurate projectile position when firing projectiles with 3D crosshair

### ISSUE THREAD

**Issue by derickso** [mwilsnd/SkyrimSE-SmoothCam#13]
![ezgif-2-62fe7f2225c8](https://user-images.githubusercontent.com/6112623/82859760-731cb680-9ecc-11ea-97b4-52496e0b1f64.gif)

Same behavior happens with vanilla HUD and SkyHUD. Position is normal Skyrim quirkiness when 3D crosshair is disabled

**Comment by kek-dev** [comment]
+1

**Comment by Cylinder-920** [comment]
Same. With and without 3d crosshair. I'm using Less Intrusive Hud II and Improve camera. Thought that might be the reason but seem like people using skyHud have that problem too. Not just magic but arrows are affected also. Work fine in 1st person although the crosshair is flickering. I'll add image later.

**Comment by Ratione** [comment]
Ditto. Been tearing my hair out over this one. No amount of Setting fiddling has changed anything. I assumed it must be something I was doing wrong

**Comment by kek-dev** [comment]
same for bows, there is nice mod to fix Skyrim's bad aim and it helps a little bit, but would be cool if the author could add full compatibility
https://www.nexusmods.com/skyrimspecialedition/mods/18524?tab=description

**Comment by mwilsnd** [comment]
I've compiled the latest version in debug mode to enable the debug line drawing for the crosshair ray and projectile trajectories. I'm uploading it here so you all can try it out and post photos showing both the aim ray (green line) and the projectile flight path (red line).

Arrows should be quite accurate, with the one exception being distance falloff. I don't try to predict that currently, I just try and get the crosshair close enough to what the normal game would do.

Magic however is still a work in progress. Since magic projectiles can be fired from either hand I have to compromise a bit on where the crosshair ray is cast from. Assuming everything is working as expected then the problem is more to do with where I'm casting this ray from and I'll need to figure out a different method.

Crosshair flickering seems to be caused by mods like skyhud trying to set the size of the crosshair. This results in flickering as both mods try and change the size. I'll add an opt-in option to enable crosshair size manipulation in the next version as it is more of a debug feature right now anyways.

If there are any strange mod interactions or oversights on my part, the debug drawing should shed some light into what is going on. Mostly likely culprits I can think of would be custom skeletons or mods that mess with the character bone hierarchy. Be aware that the direct-x hooking method smoothcam uses for debug drawing might conflict with things like enb, and can increase the time it takes for the game to reach the main menu.

To use the debug version just overwrite the DLL in your skse plugins folder with the version attached to this comment and load the game. Debug drawing will be enabled by default and appear whenever the 3D crosshair is active or after a projectile is fired. You can toggle the debug overlay on and off by pressing the insert key.

[SmoothCam.zip](https://github.com/mwilsnd/SkyrimSE-SmoothCam/files/4714120/SmoothCam.zip)

**Comment by derickso** [comment]
I can't get the game to launch using the debug .dll and ENB, but game works if ENB is disabled

With ENB enabled the fired projectile is slightly higher up for some reason compared to vanilla

No ENB + SkyHUD + SmoothCam Debug Mode:
![01](https://user-images.githubusercontent.com/6112623/83470013-f8a4e700-a435-11ea-9f4d-936646eaf796.jpg)

Also, if the player character has their back against the wall, sometimes the fired projectile clips into the wall and doesn't fire
![02](https://user-images.githubusercontent.com/6112623/83470034-03f81280-a436-11ea-90c4-4acc1e860e63.jpg)

**Comment by kek-dev** [comment]
arrows are non-accurate for my setup tho (I have few mods (like 5 or 6) for character appearance and SkyUI, that's all), **the only suspected mod is XP32 skeleton** which is used by most modded Skyrim players https://www.nexusmods.com/skyrimspecialedition/mods/1988

my game just crashes with debug .dll, but I still can provide some screenshots (SmoothCam default settings):
~3 steps https://snipboard.io/mdiR6o.jpg
~10 steps https://snipboard.io/24Q17r.jpg
~20 steps https://snipboard.io/8qM3a9.jpg
~30+ steps https://snipboard.io/mclua7.jpg

all shots were targetted at the red circle of mannequin

Skyrim.ini
f3PArrowTiltUpAngle=0.7

interesting fact:
the stronger I change the x, y offset during aiming (bow aiming offsets to be clear), the more the arrow trajectory is distorted

**Comment by Cylinder-920** [comment]
Hi. I'm unable to run the game when using debug dll while ENB d3d11.dll (v0.421) is in Skyrim folder. Without ENB, my result is in this video. https://youtu.be/d2bea9PdIWE .
- I'm using XPMSE skeleton. Character height is default 1.0
- Archer gameplay overhaul. I turn off every option in AGO MCM menu
- Improved camera
- Arrow tilt up angle is set to 0.7 in ini file

In the video there's some strange issues. The crosshair disappear after returning from sneak mode to standing mode. And it turn back on after dodging (?). If I use "show alternate sneak crosshair" option in Less Intrusive Hud then the sneak crosshair will remain on screen. But sneak crosshair isn’t affected by 3d crosshair like normal crosshair. It doesn’t connected with the green aiming line instead it will be at wherever position I config with LIH. You could also see the flickering crosshair I mentioned above. It seem to appear after dodging or in 1st mode.

Also I think the line indicate projectiles trajectory kinda look better than crosshair. Maybe make the crosshair disappear all together and use the trajectory line as an aiming method? Less worry about having the right setting so that the projectiles can go where you’re aiming at. I saw a lot of games use that method.

Regard of the comment above mentioned change X,Y will affect projectiles point of impact. It happen if 3d crosshair is disabled. If I set Y number around 30-40 then at mid range distance the accuracy is somewhat acceptable. But at long range the projectile will actually fly upward.

If bone hierarchy could affect aiming then does custom animation affect it? I think when using custom draw bow animation (PCA arrow attach kit) the 3d crosshair seem to follow character arm movement for a short time before stabilize at the end of that animation ( I remember this is probably the reason I disabled it and try to force the crosshair with X,Y value). It doesn’t happen in the video when I used the default animation (or is it AGO animation?). Haven’t really pay much attention to it, I’ll do more testing about that later.
