### ISSUE TITLE
still incompatible with mods that alter hudmenu.swf

### ISSUE THREAD

**Issue by birbrunner** [mwilsnd/SkyrimSE-SmoothCam#16]
I'm using Smoothcam with [Less Intrusive Hud II SE](https://www.nexusmods.com/skyrimspecialedition/mods/17974) and Smoothcam is causing the crosshair to just blink and stutter without moving, regardless of whether the 3d crosshair is enabled or disabled. it's not that big a deal because the game is still perfectly playable, and this is by far the best 3p camera mod out there, so i can live with it. but if this could be fixed somewhere down the road then i'd be grateful.

**Comment by Nickesponja** [comment]
I can confirm this. No options in the MCM seem to solve it.

**Comment by Nickesponja** [comment]
Ok, I figured it out. This happens when you use less intrusive Hud to set the size of the crosshair to small or too big. Values in the middle don't pose any problems. It's worth noting that with SmoothCam installed, you can't actually change the size of the crosshair with less intrusive hud, it's just the setting that causes trouble

**Comment by mwilsnd** [comment]
Yeah, it seems that mod alters the crosshair size and ends up fighting with smoothcam. I've added a new opt-in setting to enable crosshair size manipulation in smoothcam, so you can keep that setting off and let the HUD mod control it now.
