### ISSUE TITLE
Preset menu missing in latest version

### ISSUE THREAD

**Issue by themaster567** [mwilsnd/SkyrimSE-SmoothCam#23]
Attached below is a picture showing that I'm using the latest version, yet you can also clearly see that the preset menu, which is supposed to be at the bottom, is missing. Very strange.
![ScreenShot8](https://user-images.githubusercontent.com/8242023/96357708-524c3c00-10cd-11eb-9ac4-7cad8ad9040c.png)

**Comment by mwilsnd** [comment]
Now that is rather strange. You are also missing the group edit page. I wonder if the obnoxious string caching skyrim does is somehow breaking things. I'd try making a backup save, deactivating the ESP, loading the game and waiting until the smooth cam menu disappears from the MCM list. Once that happens, make a new save, quit and reactivate the ESP. If the missing options appear after the menu reloads then it was some kind of fluke, otherwise some deeper digging might be required.

**Comment by themaster567** [comment]
That was indeed the fix!

**Comment by mwilsnd** [comment]
Interesting, good to know it wasn't some deeper issue. If you have any other problems just open a new issue and I'll be happy to take a look.
